"""empty message

Revision ID: 88041b6d55cc
Revises: 2055f38e198c
Create Date: 2025-11-02 19:38:27.162645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88041b6d55cc'
down_revision = '2055f38e198c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritePlanet', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritePlanet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
